apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9jQ0vYIdOMHMgOZNSe7POckcJUARNrUj03h+SLh+9Zj2WMSuxr8K8g==,iv:iN/cr06td6yT/iw1W/CmkzCdicMEBZ5soM/bg16mCFs=,tag:AMoD6JJWiwZ8eI1Dyv7I5w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydHVqQkhCNFZBM2NkSnJB
            ekhsRnFCbUM1c3NFWWZnUlliOGh4MDcvemxFCnFvclFKQStrdmYvQWVTK0JXL3Mz
            ZEp0bjRVNmZSMlRUbnlCUVF3elNRbncKLS0tIE4rbkJGTW1qQVlya0JwWGp0Ynla
            aDZQVlhiRUIyN2c4bnFiTTltK05iYkkKDbhWKbzeizjL63+qae/BbvW5ESr7XyPt
            S/kqbxTRUqIfZEHZJ4g0XidU/GnlzHyK7LzvcetY+AevF1KMPJvh+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T23:19:24Z"
    mac: ENC[AES256_GCM,data:wF/gibHhCLeeCzeWjxY2YYByTp/2ZU6tqdEnanLsznYI8K0fuYc5STXGOv1hFOHsLjdNliOPVg8CwHOlwqFFaFS2EGUqc4fOGgViwJzcHbZOzsr0j4oUzL42MtuGznXlKWOzv+zktXJWbdLpyVYL5rfBmpAgyzPq7h+0EO4beuI=,iv:qMAOScWB7JPSZyNQ8PeCI8jGlbzl3vkvuXyilyyLyD4=,tag:9WRkZ8+CkU6RIuwRBZHI8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
