apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NYI4TZXd2S54PdgIgSHznyvYAL/Z6t8WEyBRnSk5xr32TX3SQQpRvA==,iv:7n7TOxNS+FxOEMsHP1e/9BXLuREdRnOkz3S3F957XZE=,tag:gTDFt8Gk2HH8V8WiCRmR2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYTVUM21KOVZVVVNOME84
            WDdpTzdMNWtJU3d2QzJRTURCWEgzdi81R1NVCjg1bjRlWlRwUHpzNDBPbVVCRjZJ
            RGVPSEdoY0tVSUlGYjEwa2lVaW5TZVEKLS0tIEpOK2pLSzNvRzZRVnZBTyt2SUxI
            S05XMzhjZGJQV2FHMVJuc2JSdG00SWsKqZ1bajarT5wmAd/KW9A6jAr04COpYxWW
            n/WeAybD9BQnRyru0vhYuHYpBoOp3nLJLGcR9Vyznkioe/TCJodaSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-27T00:28:19Z"
    mac: ENC[AES256_GCM,data:u2uJvbi73S+stcu6414+LV19JpLJyxrb9lTzbcF03Hem0UJ67sIa7VEUFjWckW5syJogj09UgWCo4Z3HNMaBQN6h4kqpZ8nvikU2kx/WI9/7AG3uMUhLFD4J3SQ0olPmgENFdOXJn3VEiaVTem85xUuIP14s5nGJIi2igTGOndQ=,iv:PfemVHl6x0TFKuGcMY7mVCT8JMq1NkC0j/FATPp3oqg=,tag:+9aTigf/3ebzO9SURWiSVA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
