apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZcoZqExDDUCUdqMZ2yEirl8Q3nU07e+uFW3ukACexezqNBfmzUpcag==,iv:bQ/yliBjS8fZwiOwpbuV50wfX93Yz8gKtNEBMj4cu38=,tag:zdKv5XAG9kgm94pcfiE4/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQjJGRXU3SjU2c25DeXp0
            M2hyRDNuZUl0dmV4MGxjcnhqdFFUd1RzbGx3Cnd3MmlwSnFEZFpQM3ZjRHE0Vm11
            SEp1OEVHazczdHBwNWpGS0tXL3g4TWsKLS0tIE9MYjd6VHMvK01pTUt4ckJVd293
            c0FJcmdGWWNldHkzRFRuTHp6d2lVWncKMKL+0IKaxswXTuQVDzp/9YOonGdcvqVV
            u7CSQJjPmlMT+QsNZ9Q07mJNunukYA27qjHXVDskuxDG9/Vl9R0XhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-28T22:51:06Z"
    mac: ENC[AES256_GCM,data:gdR69L8VK1B4ag+MTG/yGP1wu2d5vlT57LFW9g+mM62Dv7v7Xt0Wp8diDPEn4T5ugL+y2CWh9KG1qwYdi6lAKrLYUDRTn7tA3XrT+HdA34mVEzCjmTT+mt+KLK6kSNvpsGP5h3eIhvOTBuMxuS+9+slIdJw4S8//UbVyJNGvDqY=,iv:usmRREGh+rhfSqI/7iVzrkjZjAuKcq4b3xnPDckSM9I=,tag:e9mEjD+xQYkBDj7WJBde8g==,type:str]
    shamir_threshold: 3
    version: 3.13.1
