service:
  main:
    type: ExternalIP
    externalIP: "192.168.30.50"
    useSlice: false
    ports:
      main:
        protocol: https
        port: 81
        # Target port is the port of the "external service"
        # Defaults to "port" if not set

  ingress:
    main:
      enabled: true
      ingressClassName: external
      hosts: 
        - host: truenas.${DOMAIN_0}
          paths:
            - path: /
              pathType: Prefix
      integrations:
        traefik:
          enabled: false
        certManager:
          enabled: true
          certificateIssuer: "domain-0-le-prod"
        homepage:
          enabled: true
          name: Truenas
          description: This is a Truenas instance
          group: "{{ .Release.Namespace }}"
          icon: ""