apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboards
  - downloaders
  - media
  - gaming
  - websites
  - tools
  # - ai
  - infrastructure
  - communication
  # - decomissioned
  # - under_construction
  - external
  - observability
