apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Af344Bks1jJEtsUvH0mVa0TA0FUEkyCjQjlnQAC5aSkMb1dgTNs+xdDxgU9AqMeEtIjRj7FoF38mMRAkjG2MuxpIp0bBUM76y+bJYTeGFdsuGmE5R0zbvi181xbducbu1U263hz0cmK/ALvXydbUgS3lhmda775JMjGhLaHbmIoak7FIhveBp7Bsy0XjBcOEn+hNJ43q5bluurWo879Ls8QxHdAuESKw/AB0g87juJ2Zi4YGZgbgoP6SvzIMbTqKWTQPPShrKC0sBW75K3GM6bECut1mbabNyQQUVBvuDbCq482ERBoP0sP9fhqwrzyJtYu87ARden3oW9x0SJyLJLwfaQjvS1zdzZqXCX+XYhgLQqPPakeG15IIc2hpITYU,iv:COASHbzrzSlcflYqvrW6VxwsA/8w/eObEHw/MIsBj9E=,tag:17VQH02xBGGON4q4ne5p7g==,type:str]
    identity.pub: ENC[AES256_GCM,data:7jPwN5hEFqb5xKDrGika6G00gIKu/xVQLDMm17eb6tk3OgsXpc08uspkZrDmZMIZwcVSm8qAXTOOiJ/8567QobMlq3KuaMM8j5kYlsHTylaXBv03Z7mngpvz47y0Le9rqWV3Piz4ik1PRK6RJ3l1tICF5p52ps7g3w+6+1sI58fcF8BZCYwdKRc6mDMLg0HloXXRXTqUOO7JgUj40WndtiaCr6EuqwOTVwtTmLpqYEz1KHlU8yuLIFD84KpgCxe4m00VXpYlkDyw5hO3uQ==,iv:odId280FNBfA/J+8uJCzpstmKtozLjZAugzAVezyYGg=,tag:TnI9LwjbOz3vSGNEASeylA==,type:str]
    known_hosts: ENC[AES256_GCM,data:j20MWU6VwRPWS1tW1xZgmIylwKP7fcNEZM3gGClvHMreKB4SURsCG56BPOzi0P3J/XRwPnqZnn2CdPc+JY3SH2QsdI3niJTLcaRXkgId3yFQIrLWDwBJesGsF+K96a0Y1/T2nTn0FaMzJsr70tdjeD4O+uX8QDhJjSl2h42NjpHsVCkPo0xUQGzqjdGDtccmMPVSWSoccDbOgyEU+dM/jLyT9r4j8NvcvPHB,iv:8V458929+NAMVHuhlKQMt0mXhZWQrX0uohKqu/xFW0U=,tag:yYVLtNgOYJc+boYYyyH63g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcjFldGE5dktQQTdaMjNs
            UG5wVW1nRkJ5bDRjUFo4djFtbThjd0FmMXdnCnBDTWEzUnVEZ1EwZnc2MVNwUUV2
            aDI3cWVwakpiVmRwTWhqR0JQUm41c0kKLS0tIEdXOEY2VTU4T3hPbGZVcXloTFgv
            WFlUMzJhemM2ZkFtdU5qclVsei8zMzAKeDbYV4YbxNdB0JWArGanl9Hby/ewsJZR
            1kgvp9a+6BVugsQNQ62M4n6M3Md7m8kBDpkE5/tVBAobA8haaTIStQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T17:58:49Z"
    mac: ENC[AES256_GCM,data:kNqUDdHIDK8Cm4zs07Bs5FiEdSsvTumpKOcE8oBW5Yu2sUZBaaOfzzYHd4ejuu35E6nJV4R+l+NWanfvzOY+VX4CiS4KpyTsFkvZeWy4U6jMREvQlUKwz3H1CCkPX07XXdBnQncnxajtkOS+4FGYhCvIZHVf2s/6roHPGEX55wc=,iv:GNHgLuJfLrURPVjz6p2mV9U76GKijqysY/veVxLOw6g=,tag:3DSNYM+AueqpZT5pkjMHyQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
