apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fp47RTjzuxp2ChVj+QeUZAzfsWR3wLSsKsdj11L3fLUbWeUylR10MsWmirPKwknAfchEm7cvc67FI/35PXK3a3YfGRRfoN66lm3FIiILZSJ48XecJa6Q9tej9z1nJdQtRbMR6C9AiB83IVL7uSJ/5VRtCR+LZinJGFzXkYd2EA45yQOn42noGdO6xLvkjeiM03DwGnBdIcFtKmmR14/Xuw0GhvyjShIq2jxJB+0bcyvTKX56NYQCbOxFHp7M3qZBBmeG170tj2qEq4PhBXi99v4AW6ULi41K0X4yuKZ373U/e4k5vhsl4mhIYBV30IL9Q2iB0YFGnUTHTut3i5TcZcSYv858n23E83KD1kOvsq/JHNV2TPqXDnwumYVRqM6z,iv:W5pzYXu1TKxq2quGr+PO2lg7vd0onmUJZ/Rq07WJXKw=,tag:rTLvg8qC+SL+NyJUUgH9Dg==,type:str]
    identity.pub: ENC[AES256_GCM,data:OmlbQ0fB8BsqvDsjik/0adVbBZe1X31WInU4aIweJseR74xUjWLhIGrHDuZ0cVn+/YD3Pl1H5P8pQVhvyWGhoOq8oIMCA03glCF5ncLWQEOmcxeE4FyvK5EKcnmYSewWSl1YAlclQQZ22xniGyLqLUTHG9DkYCzQ9XXlY4+1kELpIhlGkXqrjufh3hVFI8sPr28uqhrYeoZTEx/1t4x12k96NXsW/ciLvlN99hir5wLmrpXPqC7MQtNPZsjlXziGKF31mCcusQiQ6lHhMQ==,iv:Bxvbq6rSgUGKRgeXk4HRIcVTKtZxpz9bVcUVwHSJ9H8=,tag:+slR5Q6C0yFlTOpaLZV8PA==,type:str]
    known_hosts: ENC[AES256_GCM,data:M4OryfySgqySXfgyJIjbsuq+UVZ+VOhnfHO2w0gkqwpTmprJjQvb7OciqOPA72J7FwYEYVjfihQgr7QYeaNbbWfffRqqx2M67aH48x3b4GnAgTG6UOaQCWbYaP2qZz8TphNcvmxvHkZUsFki5GwJnTurmNVp+wnxzyr35TOGF1GNdelpNaq5uOLTBXDTgN9AZfjUwibjCR8b5LjGdRbvzSy6ALJI6Jizs1ux,iv:t4njzl78rva/Vq3tTZc5Th5go04Tnf4AVS8+jH2GjZk=,tag:ojzWrhl+UtJpu0gYfA0ixQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbUlBZ3VEWTZlMUgyMzBC
            TUl4ZnZRQ0gwUWdGN2xEWnhsWEpaOW1nQ3lFClI2ZXc0TUdjbnpyYWE1YWc3UzB0
            SDRQUldaOXJEVzNwTk14Y1NDS3g2U0EKLS0tIFhkRVErSXNFcEQyQURFYllpL0l5
            N2VGWGRISjBMRCtFdDkrOWVGK0VSODQK8LF2V/+AR4U9ePc9UR8jeGUTQWKamwKF
            rFU/g7k82n4IFs7SaDCF8ybGqTk21dtZEcLRLikP3Z7M52nxVDBPeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-10T21:45:47Z"
    mac: ENC[AES256_GCM,data:nGIpIBrMx5X80MaCZOgdeRnAwUTS7n9gwUItLF2R4WK3WC2injdNQBPQgjQiEsbvazv3wRv/aOiATcPkhVEtmf6A75wxaOZ0pgwzE5M4V/aTbnXN1UOQmYZeoXWBUrlu+9uWOEJWlc7i6V3UmrDuC8GUliky1D6zppPwbrxGLys=,iv:7HCZ3o4qPkz27FEZKa81Sv27X8Qs/SWN8SVxvCR5isg=,tag:WAEK2acEjJMsg4KBNf4b0g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
