apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JzcFe2Q5+iETQdQ/hDtxKg4oITFuR+eY5L5g4SxTXUuAcI/FctWgVGLLoYOiryF9z98D5D8x4kbtzKqGLp6fqRF7vySpkFPS0A23cbWg9ipTeMhLHTtW6kfnIv72YBjKZbyO0OtwCs7Z/sCwoUi4YdU8uusZ0sESXsErLvExLZKFouQA94Z+M51cTsmWAX5a9ojAH+PtTe7W3KP3zYTpoOgreluyfJObpXTTsJDZ2tc89RmhTeUmlOinXIOMBUyQWCiPpDIpVTMZ3Vn7HdnuAmYfU1FRZWX8KnHIGGWKHZksVD3PezL9qj/F7WFkGhLCe31gWQn3vEo4rLuYizFGiSbJRkUTNICcHLv/mMWGFgTNwlClmKU1vxLnSsM1Dp3f,iv:/mbfSb7LE5TUxVpaKF/dKTr8V1dI271ZVGb2yyuzD2I=,tag:xnC9DUClAY6Wdj/1ZCBePg==,type:str]
    identity.pub: ENC[AES256_GCM,data:d2Qpid6NksrJFD+CiaCelxRZPg6R1O5wzbWbfTfT8ZTb+YPUnMbggNsKjqt7GGa8Q5f+EX/hIuYQFBlS3RrcCkoO9dm0CHHJfL8EMZ0ySmSDIzxakKu4izZodRKdUJy2usg7hevLbEZ/gjScrkwfg3rc6MbnajMikXrBcl3lk1+tAKOqSmQHeJQEdzFFquvv+qtEoTka/zS4n5ut8A4WWL02+9hr1AUL1wFFCPjAsEedOuCzfR9ySi1Gsk4I/4zEFYSecH5aqP8NHw9dHQ==,iv:DB9TCmZMkD8wslPg52wwJzucZLq5aonsb6CxVPacCpI=,tag:59oXm+L9JapbYy33zehdyQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:zXIkylEAVXwozkzNkgF+fHLhyKrwUxl8wRli7ydLQfgZO50WYXwIX9cruUPj1yXRpzFwBHUFFBZNhkf2PIF25AZgpY/WzGmElgi9O6Um976/Nyqu1gHEK1NwH258IgC2sOUUEp45MqY9oBfrs83Au1aTIaQAeOtS6iOnINsioCy+FS+/PbYCF1eumttPu5b18z4ZC9lqF/SD+Cg0S55WynDhO1RwyDCct8JP,iv:uKv3uKIHnamJNiQ7jlVbmnb0GXbmgLUdKizXXYGLAQ0=,tag:X70+PkUsxlR00v+0xtTzNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1k26ujnyjzw0y2sd72lyayn694luyr9agswjuklrtn8j3a5vseuaqsvruad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN2tCeEpkQTlmZGdlSjlT
            Ti92WTlRVDlhZFh2M2MvYkJNclRmTnlkcHd3CjdDaUV2VXVpQ243WUF2ZlF1ODVY
            TmVnMzU4OWVlcTVaRzlSM1pxZngzYXMKLS0tIEd0WWZyVkEweSt5dHk1SWkvbU1H
            SXFXOSthbm5GWVY3SHFFRGlwMk15VVkK6NtJ4waS29SLcnGvyG6bQW9ifeH3REfd
            Gbq0Qs7lPIgUGYfP5XKRfQ+9vB+QQZHvIO/TqZsuCs9sBRaf2fgQzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T03:35:16Z"
    mac: ENC[AES256_GCM,data:nVihV0b6XW+YpIQ+syLuX0cQJDN1rfAm/m9swPFfHjenBCOw6aMHMvTEUlIHwfQI6H6J00fv82EC3Ox6H03w1Y/u2v4wsb2SKavaQHeardkq1R2Wd3bRAP5lUJXpN2UPSysavrEso9hIhgcrVsX/VtOOL6bkBh9U59yLt37vXTI=,iv:rc5FGUcrexD8iKLykhnoLE/I0vHUh4I7VhZNLyHdzIU=,tag:TxGhD1h8hOO7n1sqF3XOXQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
