apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - helm-release.yaml
configMapGenerator:
  - name: grafana-dashboards-values
    files:
      - values.yaml=dashboards-values.yaml
    options:
      disableNameSuffixHash: true
