apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homelab-ai.yaml
  - homelab-downloaders.yaml
  - homelab-jellyfin.yaml
  - homelab-flux.yaml
  - homelab-flux-test.yaml
  - homelab-gitops.yaml
  - _template.prometheus-rule.yaml
